### ISSUE TITLE
Update "performList" in member_updated "trigger" with latest data

### ISSUE THREAD

**Issue by naz** [TryGhost/Zapier#13]
### Problem

There should be a way to update name, note, label and other fields in external services when this data is updated within Ghost. Having this update would enable following example Zaps:
- [x]  When a member is updated in Ghost ⇒ update the member's details in Mailchimp (including name, labels, note) (https://zapier.com/shared/939105b7f2fa9506bd2003150d42c1d11088ec88 - needs conditions/filtering in Zap for proper functioning)
- [x]  When a member unsubscribes in Ghost ⇒ they're unsubscribed in Mailchimp (https://zapier.com/app/editor/102674034/ - uses filter comparing current/previous object's subscribed field values)
- [x] ~When a paid-member is added to Ghost ⇒ they're added to Mailchimp, with a label of what plan they're on. (needs https://github.com/TryGhost/Team/issues/402 and trigger data updates to enable this scenario).~ needs changes in Members

### Todo:
- [x] make an update in `member_updated` trigger based on data served form Ghost Admin API
- [x] create zaps described above
