### ISSUE TITLE
Update "inputFields" schema in create_member "create" with latest data

### ISSUE THREAD

**Issue by naz** [TryGhost/Zapier#14]
refs https://github.com/TryGhost/Ghost/issues/12273

### Problem

Current "inputFields" schema is out of sync with current Ghost core implementation. This should be updated and possibly put in direct dependency with [member's JSON Schema](https://github.com/TryGhost/Ghost-SDK/blob/8260eca/packages/admin-api-schema/lib/canary/members-add.json) (this needs thinking and research)

### Example Zaps this update should enable
- [x] When a TypeForm is submitted ⇒ create a member in Ghost with a label of "typeform" and a `note` populated with one of the typeform fields (https://zapier.com/shared/07000fe42b2f387cd1569331862fef96c1461467)
- [x] When a TypeForm is submitted ⇒ create a member in Ghost with a label of "gift" and give them a complimentary subscription ⇒ [Delay for] 52 weeks (in Zapier) ⇒ then remove the complimentary subscription in Ghost ⇒ Send the member an email saying their Gift subscription has ended (with Zapier email)
  - [x] needs "update member" "create" trigger in Zapier Integration
  - [ ] continue progress in https://zapier.com/app/editor/102006858

### TODO
- [x] update current implementation with fields needed for Zaps (https://github.com/TryGhost/Ghost-Zapier/pull/26)
  - [x] `note`
  - [x] `comped`
- [x] check how to improve maintenance and have this data in sync through automation - we want to expose as few fields as possible for non-stable endpoints. Because of this syncing with json schema repository directly would not be desireable.
- [x] create Zaps from above list
- [x] check progress on TryGhost/Ghost#12270 
- [x] check copy updates with @peterzimon (https://ghost.slack.com/archives/C02G9E68C/p1602836494357100?thread_ts=1602821427.356500&cid=C02G9E68C)
