### ISSUE TITLE
Add new trigger for "post scheduled" event/webhook

### ISSUE THREAD

**Issue by naz** [TryGhost/Zapier#15]
### Problem

People need to have access to scheduled posts event to allow further automation through Zapier.

### Current state
There should be a way to subscribe to post scheduling webhook which is already available within Ghost core. Webhook's payload needs checking if all needed information (see example Zaps) is there.

### Example Zaps:
- [x] When a post is scheduled in Ghost ⇒ send a notification to Slack saying "[author.name] scheduled [post.title](post.previewlink) to be published at [time] [timezone] on [date]"

### Todo:
- [x] Check if all needed data is available in webhook's payload (in Ghost core)
- [x] Implement trigger for "post scheduled" webhook
- [ ] Create Zap from example Zaps list
