### ISSUE TITLE
Add member "search"

### ISSUE THREAD

**Issue by naz** [TryGhost/Zapier#17]
partially blocks https://github.com/TryGhost/Ghost-Zapier/issues/16

### Problem

When creating a Zap there's a need to be able to check if member already exists within Ghost.

### Example Zaps
- [x] When a subscriber is added in Mailchimp, and that email address already exists in Ghost, update any missing attributes in Ghost (such as name, or label)
- [x] When a person buys a subscription in Paypal ⇒ create a member in Ghost (optionally with a label) (**NOTE**: [needs research ](https://www.notion.so/ghost/Research-PayPal-triggers-filters-to-allow-reacting-to-subscription-changes-c9d61194e5a14a1cadb113591d08d9f9)into what's possible through PayPal first)

### Technical solution

Need to add "search" (similar to `author` search) functionality along with possible changes in Ghost-Admin-API SDK (this needs checking).

Reasoning behind we are adding "search" and not for example "create or update" action. Search is a function that is suggested as the best practice by Zapier:
> Create actions can also update existing items—something often **paired with a Search** to locate the item **needing updates** first.
Search actions, then let users do more with the data they’ve already added to your app. Perhaps they want **to avoid adding duplicate items**—and prevent errors from your API.
....
Search actions can **optionally create** items if nothing is found for the search. 

([reference](https://platform.zapier.com/docs/search-create))

### Todo
- [x] check if/what changes are needed in Ghost-Admin-API SDK (search parameter [use/stability discussion](https://www.notion.so/ghost/Member-s-search-parameters-d607fb68c03f44d7a4611586a6a7ca96))
- [x] implement "search" for "member" resource - [PR](https://github.com/TryGhost/Ghost-Zapier/pull/29) using `search` query parameter, alternative could be using `?filter` query parameter
- [x] implement Zaps (ones that are possible to)
